:audio: audio
:clipping: image
:ephemera: image
:manuscript: document
:pamphlet: document
:periodical: document
:photograph: image
:poster: image
:scholarship: document
:sheetmusic: document
:transcript: document
:video: video
